### PR TITLE
fix(windows): suppress experimental coroutine deprecation for MSVC 14.5+

### LINKED ISSUE #474: fix(windows): suppress experimental coroutine deprecation for VS 2026 / MSVC 14.5+
## Description

Building the app on Windows with Visual Studio 2026 (MSVC 14.5+) fails due to a breaking change in the STL. The `flutter_local_notifications_windows` plugin uses `<experimental/coroutine>` which was removed in MSVC 14.5+, replaced by the C++20 `<coroutine>` header.

## Error

```
error C2338: static assertion failed: 'error STL1011: The /await compiler option,
<experimental/coroutine>, <experimental/generator>, and <experimental/resumable>
are deprecated by Microsoft and will be REMOVED SOON. They are superseded by the
C++20 <coroutine> and <generator> headers. You can define
_SILENCE_EXPERIMENTAL_COROUTINE_DEPRECATION_WARNINGS to suppress this error for now.'
```

## Fix

Add `-D_SILENCE_EXPERIMENTAL_COROUTINE_DEPRECATION_WARNINGS` to `windows/CMakeLists.txt` global compile definitions until `flutter_local_notifications_windows` is updated to use C++20 coroutines natively.

```cmake
add_definitions(-DUNICODE -D_UNICODE -D_SILENCE_EXPERIMENTAL_COROUTINE_DEPRECATION_WARNINGS)
```

## Environment

- Visual Studio 2026 Professional (MSVC 14.51)
- Windows 11 Pro 26H2
- Flutter 3.44.0

## Notes

A local fix is already stashed on branch `feat/451-room-role-abstraction` and can be applied to a dedicated branch when ready.

### PR DESCRIPTION
**Pull request by smfernandez**
## Summary

- Adds `-D_SILENCE_EXPERIMENTAL_COROUTINE_DEPRECATION_WARNINGS` to `windows/CMakeLists.txt` global compile definitions
- Unblocks Windows builds on Visual Studio 2026 / MSVC 14.51+ where `<experimental/coroutine>` is a hard error
- Affects `flutter_local_notifications_windows` and `permission_handler_windows` plugins
- One-liner cmake change; remove this once upstream plugins migrate to C++20 `<coroutine>`

## Test plan

- [x] `flutter build windows` succeeds on MSVC 14.51+
- [ ] No regression on earlier MSVC versions (define is a no-op there)

Closes #474

🤖 Generated with [Claude Code](https://claude.com/claude-code)

### CODE REVIEW

File: windows/CMakeLists.txt [hunk 1]
```diff
@@ -32,6 +32,11 @@ set(CMAKE_CXX_FLAGS_PROFILE "${CMAKE_CXX_FLAGS_RELEASE}")
 # Use Unicode for all projects.
 add_definitions(-DUNICODE -D_UNICODE)
 
+# Suppress MSVC deprecation errors for <experimental/coroutine> used by some
+# plugins (flutter_local_notifications_windows, permission_handler_windows).
+# Remove once upstream plugins migrate to <coroutine>.
+add_definitions(-D_SILENCE_EXPERIMENTAL_COROUTINE_DEPRECATION_WARNINGS)
```
Comment (Quantumheart) [inline windows/CMakeLists.txt:38]: remove once upstream plugins? What plugins?

Comment (smfernandez) [reply windows/CMakeLists.txt:38]: The two plugins that use `<experimental/coroutine>` and trigger the MSVC 14.5+ error:
- `flutter_local_notifications_windows` (Windows backend for local notifications)
- `permission_handler_windows` (Windows backend for the permission_handler plugin)

Both are pub.dev packages we depend on transitively. Once their maintainers update their C++ code to use the C++20 `<coroutine>` header instead of `<experimental/coroutine>`, we can drop this define.
